# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: For New York
email: support@bondstreet.com
description: >
    Updating the description from prose.io
baseurl: "/for-ny" # the subpath of your site, e.g. /blog
url: "http://bondstreet.github.io" # the base hostname & protocol for your site
twitter_username: onbondstreet
facebook_username: onbondstreet

# Collections
collections:
    'events':
        output: true

# Build settings
markdown: kramdown
exclude: [node_modules]

# Prose.io options
prose:
    siteurl: 'http://bondstreet.github.io/for-ny'
    media: 'images'
    ignore: [ '_config.yml',
        '_includes/footer.html',
        '_includes/head.html',
        '_includes/header.html',
        '_includes/icon-facebook.html',
        '_includes/icon-facebook.svg',
        '_includes/icon-twitter.html',
        '_includes/icon-twitter.svg',
        '_includes/landing-header.html',
        '_includes/landing-nav.html',
        '_includes/manifesto-section.html',
        '_layouts',
        'css',
        '_css',
        '.gitignore',
        'README.md',
        'feed.xml',
        'index.html',
        'package.json' ]
    metadata:
        _posts:
            - name: 'title'
              field:
                element: 'text'
                label: 'Title'
